const I18N = {
en: {
  "nav.services": "Services",
  "nav.why": "Why us",
  "nav.gallery": "Gallery",
  "nav.faq": "FAQ",
  "nav.reviews": "Reviews",
  "nav.contact": "Contact",
  "nav.call": "04 396 3384",
  "nav.whatsapp": "WhatsApp",
  "hero.kicker": "Al Karama, Dubai · Handyman & maintenance",
  "hero.title": "Every fix around the house,<br>handled by one team.",
  "hero.sub": "Handyman and maintenance services for Dubai homes and offices — electrical, plumbing, AC and appliances. Based in Al Karama, serving all of Dubai.",
  "hero.cta1": "Book a visit",
  "hero.cta2": "WhatsApp us",
  "trust.t1t": "Call us",
  "trust.t1d": "04 396 3384",
  "trust.t2t": "Handyman · Maintenance",
  "trust.t2d": "Electrical, plumbing & AC",
  "trust.t3t": "Al Karama based",
  "trust.t3d": "Serving all of Dubai",
  "stats.samedayNum": "One call",
  "stats.sameday": "fixes around the house",
  "stats.tradesNum": "Electrical · plumbing · AC",
  "stats.trades": "maintenance specialists",
  "stats.rateNum": "Al Karama",
  "stats.rate": "serving all Dubai",
  "stats.visitNum": "Quote first",
  "stats.visit": "clear pricing before work",
  "services.kicker": "What we do",
  "services.title": "Installation and repair, done right",
  "services.s1t": "Electrical repairs",
  "services.s1d": "Fault finding and repairs for switches, sockets and circuits.",
  "services.s2t": "Plumbing fixes",
  "services.s2d": "Leaks, taps, blockages and fittings — fixed quickly and neatly.",
  "services.s3t": "AC maintenance",
  "services.s3d": "Split AC servicing and minor repairs to keep you cool.",
  "services.s4t": "Appliance repairs",
  "services.s4d": "Washing machines, fridges and small appliances diagnosed and repaired.",
  "services.s5t": "Fixtures & fittings",
  "services.s5d": "Curtain rods, TV mounting, shelves — fitted securely.",
  "services.s6t": "Sealant & touch-ups",
  "services.s6d": "Silicone re-sealing and small paint touch-ups, finished cleanly.",
  "why.kicker": "Why choose us",
  "why.title": "One team for the whole home",
  "why.intro": "Small jobs pile up — our Al Karama team handles electrical, plumbing, AC and appliances in one visit, so your home is sorted without chasing four contractors.",
  "why.l1t": "All trades in one visit",
  "why.l1d": "Electrical, plumbing, AC and appliances — one booking covers it.",
  "why.l2t": "Al Karama based",
  "why.l2d": "Quick to reach anywhere in Dubai.",
  "why.l3t": "Upfront pricing",
  "why.l3d": "You approve the price before we begin — no surprises.",
  "why.l4t": "Easy to reach",
  "why.l4d": "Call or WhatsApp on 04 396 3384 — we will take it from there.",
  "gallery.kicker": "Our work",
  "gallery.title": "Neat work, done properly",
  "gallery.c1": "Secure wall mounting, done neatly",
  "gallery.c2": "Clean silicone sealing, professional finish",
  "gallery.c3": "Electrical repairs handled safely",
  "reviews.kicker": "What people say",
  "reviews.title": "Trusted across Dubai",
  "reviews.more": "Find us on Google — see our location and reviews",
  "faq.kicker": "Good to know",
  "faq.title": "Frequently asked questions",
  "faq.q1": "Which areas do you serve?",
  "faq.a1": "We are based in Al Karama and serve homes and offices across Dubai.",
  "faq.q2": "Do you give quotes before starting?",
  "faq.a2": "Yes — you approve the price before we begin any work. No surprises.",
  "faq.q3": "What kind of jobs do you take?",
  "faq.a3": "Electrical and plumbing fixes, AC maintenance, appliance repairs and general handyman work.",
  "faq.q4": "How do I book a visit?",
  "faq.a4": "Call or WhatsApp us on 04 396 3384 and tell us what needs fixing — we will take it from there.",
  "contact.kicker": "Get in touch",
  "contact.title": "Book your visit",
  "contact.addr": "Address",
  "contact.phone": "Phone",
  "contact.hours": "Hours",
  "contact.hoursVal": "Hours: by appointment | Call for availability",
  "contact.cta": "Call to book",
  "contact.cta2": "WhatsApp us",
  "footer.tag": "Handyman & maintenance · Al Karama, Dubai"
}};

document.addEventListener("DOMContentLoaded", function () {
  var btn = document.getElementById("menuBtn");
  var nav = document.getElementById("mainNav");
  if (btn && nav) { btn.addEventListener("click", function () { nav.classList.toggle("open"); }); }
  nav && nav.querySelectorAll("a").forEach(function (a) { a.addEventListener("click", function () { nav.classList.remove("open"); }); });
  var dict = I18N.en || {};
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var k = el.getAttribute("data-i18n");
    if (dict[k] !== undefined) { el.innerHTML = dict[k]; }
  });
});
